version: '3'
services:
  trebizond_1:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_1
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_1 1 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6530:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_1
  trebizond_2:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_2
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_2 2 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6531:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_2
  trebizond_3:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_3
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_3 3 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6532:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_3
  trebizond_4:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_4
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_4 4 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6533:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_4
  trebizond_5:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_5
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_5 5 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6534:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_5
  trebizond_6:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_6
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_6 6 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6535:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_6
  trebizond_7:
    image: systematic-chaos/trebizond:latest
    container_name: trebizond_server_7
    command: node trebizond-redis-server/dist/trebizond-redis-server/trebizondRedisServer.js eth0:6530 redis_7 7 dockerEndpoints.txt
    volumes:
     - .:/home/trebizond
    ports:
     - "6536:6530"
    networks:
     - trebizond-back-tier
    links:
     - redis_7
  redis_1:
    image: redis:4-alpine
    container_name: trebizond_redis_1
    networks:
      - trebizond-back-tier
  redis_2:
    image: redis:4-alpine
    container_name: trebizond_redis_2
    networks:
     - trebizond-back-tier
  redis_3:
    image: redis:4-alpine
    container_name: trebizond_redis_3
    networks:
     - trebizond-back-tier
  redis_4:
    image: redis:4-alpine
    container_name: trebizond_redis_4
    networks:
     - trebizond-back-tier
  redis_5:
    image: redis:4-alpine
    container_name: trebizond_redis_5
    networks:
     - trebizond-back-tier
  redis_6:
    image: redis:4-alpine
    container_name: trebizond_redis_6
    networks:
     - trebizond-back-tier
  redis_7:
    image: redis:4-alpine
    container_name: trebizond_redis_7
    networks:
     - trebizond-back-tier
networks:
  network-back-tier:
    driver: bridge
    imap:
      driver: default
      config:
       - subnet: 172.16.238.0/24
